version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=simple_bank

  api:
    container_name: simple_bank
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "DB_SOURCE=postgresql://root:pass@postgres:5432/simple_bank?sslmode=disable"
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]